### PR TITLE
Mobile sharing folder rename modal

### LINKED ISSUE #1764: Renaming Shared folder - Modal not used (mobile)
**Describe the bug**
On mobile, when renaming files / folders in the home file browser we show a modal but this is not appearing when renaming shared folders (and it's not possible to rename without the modal as tapping the input will open the folder) 

**To Reproduce**
1. Go to shared folders on mobile
2. Click the kebab menu button and choose rename
3. Attempt to interact with the input field and see that it's not possible because it will open the folder when tapped.

**Expected behavior**
When on mobile, a rename modal should be shown to the user

**Video**

https://user-images.githubusercontent.com/3982665/142510188-17fde7da-9bf3-43b6-aff9-3407cc82ed88.MP4

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.1
 - Browser: Safari 15

### PR DESCRIPTION
**Pull request by RyRy79261**
closes #1764

---

Submission checklist: 

- [x] Functionality
- - [x] Feature works as intended after change

- [x] Layout
- - [x] Change looks good in the desktop web ui
- - [x] Change looks good in the mobile web ui

- [x] Theme
- - [x] Components / elements inspected in light mode 
- - [x] Components / elements inspected in dark mode

### CODE REVIEW

File: packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx [hunk 1]
```diff
@@ -228,79 +270,136 @@ const SharedFolderRow = ({ bucket, handleRename, openSharedFolder, handleDeleteS
...
+              onClose={() => setIsRenaming(false)}
+            >
+              <FormikProvider value={formik}>
+                <Form className={classes.renameModal}>
+                  <Typography
+                    className={classes.renameHeader}
+                    component="p"
+                    variant="h5"
+                  >
+                    <Trans>Rename folder</Trans>
```
Comment (FSM1) [inline packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx]:
```suggestion
                    <Trans>Rename shared folder</Trans>
```

**Review by FSM1 — APPROVED** [review]

**Review by tanmoyAtb — APPROVED** [review]
looks good!

**Review by asnaith — APPROVED** [review]
Working great on iOS
