### PR TITLE
[STORAGE] Rename file in bucket

### LINKED ISSUE #1330: Add Rename option to Kebab menu for files in a bucket
**Description**
Options missing from Kebab menu - Rename 

**Steps to Reproduce**
1. Login to ChainSafe storage
2. Create a bucket
3. Upload items to bucket
4. Click on the kebab menu for one of the items

**Observed behavior**
Only Move, Delete options are available

**Expected behavior**
The Rename option should be avilable in the menu. Validation of the desired name should be added to ensure that only valid names are submitted.

The edit mode should be mobile responsive (Modal dialog with buttons instead of inline editing)

**Screenshot**
Screen Shot 2021-07-23 at 1 34 48 PM

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version : 91.0.4472.114

### PR DESCRIPTION
**Pull request by FSM1**
Closes #1330

### CODE REVIEW

File: packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx [hunk 1]
```diff
@@ -213,11 +213,12 @@ const FileSystemTableItem = React.forwardRef(
 
     const formik = useFormik({
       initialValues: {
-        fileName: name
+        name: name
       },
       validationSchema: nameValidator,
       onSubmit: (values) => {
-        const newName = values.fileName?.trim()
+        debugger
```
Comment (Tbaut) [inline packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx]:
```suggestion
```

**Review by Tbaut — APPROVED** [review]
Works perfectly, just a forgotten debugger and lint failing

**Review by tanmoyAtb — APPROVED** [review]
Looks good!
