### PR TITLE
Clear error message when the charge got rejected

### LINKED ISSUE #1922: "Confirm plan change" error message persists on modal
**Description**
After invoking an error message on the "confirm plan change" modal, if you leave and return (even after selecting a new payment type) the original message will still be displayed. 

**Steps to Reproduce**
1. Go through the payment flow to upgrade a plan
2. Try to pay for a plan with a credit card that will fail
3. Observe the failure message
4. Click "go back"
5. Choose crypto as the payment type and return to the "confirm plan change" 

**Observed behavior**
Original error message relating to the failed credit card transaction is still displayed

**Expected behavior**
Error message should not be retained after navigating away from the modal and returning

**Video**

https://user-images.githubusercontent.com/3982665/152876853-610a907a-be99-4219-9f8d-f8f21c0e7a22.mov

**Desktop:**
 - Not specific to any browser / os combo.

### PR DESCRIPTION
**Pull request by Tbaut**
closes #1922

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

### CODE REVIEW

**Review by FSM1 — APPROVED** [review]

**Comment by Tbaut** [comment]
Added another nit to reuse some code @FSM1

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx [hunk 1]
```diff
@@ -7,6 +7,7 @@ import { useBilling } from "../../../../../Contexts/BillingContext"
 import { useFilesApi } from "../../../../../Contexts/FilesApiContext"
 import ConfirmPlan from "../Common/ConfirmPlan"
 import { t } from "@lingui/macro"
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx]:
```suggestion
```

**Review by asnaith — APPROVED** [review]
💯 All looking good now 👍
