### PR TITLE
Prevent multiple file/folder renames [storage]

### LINKED ISSUE #2089: [Storage] Actioning rename option opens all files / folder in edit mode
**Describe the bug**
If you have more than one file or folder and you attempt to rename one of them all will be in edit mode. 

**To Reproduce**
1. Loging to storage
2. upload two files
3. create two folders 
4. try to rename a file / folder 

**Expected behavior**
Only the file / folder you selected should enter "edit mode". 

**Video**

https://user-images.githubusercontent.com/3982665/162815944-91d6186d-f414-4463-ab9a-2ba0ff59d94b.mov

Desktop:
- Not OS / browser specific

### PR DESCRIPTION
**Pull request by tanmoyAtb**
closes #2089

Also added the on click outside with rename fields in storage.

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui

#### Theme
- [x] Components / elements inspected in light mode

### CODE REVIEW

**Review by asnaith — APPROVED** [review]
Working nicely and adding the click outside was a good idea 👍

(Test failures seem to be only because bucket deletions are still not working on stage)

File: packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx [hunk 1]
```diff
@@ -130,12 +130,12 @@ interface IFileSystemTableItemProps {
   isOverUpload: boolean
   selected: ISelectedFile[]
   file: FileSystemItem
-  editing?: string
+  editing?: ISelectedFile
```
Comment (Tbaut) [inline packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx]: Could we name this `editingFile`?

File: packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx [hunk 2]
```diff
@@ -234,7 +234,7 @@ const FileSystemGridItem = React.forwardRef(
           >
             {icon}
           </div>
-          {editing === cid && desktop ? (
+          {editing?.cid === cid && editing.name === name && desktop ? (
```
Comment (Tbaut) [inline packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx]: pretty sure I broke this in the past, because I didn't realize the name made sense for folders for MFS, since they don't have a unique cid
```suggestion
          // checking the name is useful for MFS folders since empty folders all have the same cid
          {editing?.cid === cid && editing.name === name && desktop ? (
```

File: packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx [hunk 3]
```diff
@@ -281,16 +284,16 @@ const FileSystemTableItem = React.forwardRef(
           data-cy="label-file-item-name"
           ref={preview}
           align="left"
-          className={clsx(classes.filename, desktop && editing === cid && "editing")}
+          className={clsx(classes.filename, desktop && editing?.cid === cid && editing.name === name && "editing")}
           onClick={(e) => !editing && onFolderOrFileClicks(e)}
         >
-          {editing === cid && desktop
+          {editing?.cid === cid && editing.name === name && desktop
```
Comment (Tbaut) [inline packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx]:
```suggestion
           // checking the name is useful for MFS folders since empty folders all have the same cid
          {editing?.cid === cid && editing.name === name && desktop
```

File: packages/storage-ui/src/Components/Pages/BucketPage.tsx [hunk 4]
```diff
@@ -97,8 +97,8 @@ const BucketPage: React.FC<IFileBrowserModuleProps> = () => {
       .finally(refreshContents)
   }, [bucket, storageApiClient, refreshContents, pathContents, currentPath, addToast])
 
-  const renameItem = useCallback(async (cid: string, newName: string) => {
-    const itemToRename = pathContents.find(i => i.cid === cid)
+  const renameItem = useCallback(async (item: ISelectedFile, newName: string) => {
+    const itemToRename = pathContents.find(i => i.cid === item.cid && i.name === item.name)
```
Comment (Tbaut) [inline packages/storage-ui/src/Components/Pages/BucketPage.tsx:102]:
```suggestion
     // checking the name is useful for MFS folders since empty folders all have the same cid
    const itemToRename = pathContents.find(i => i.cid === item.cid && i.name === item.name)
```

**Review by Tbaut — APPROVED** [review]
Nice, it's working well, and I learned that all empty folders have the same cid on IPFS MFS.
Just suggested a  name change and adding some comments to remember my in the future to not remove this name check.

File: packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx (hunk 1 above)
Comment (tanmoyAtb) [reply packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx]: 👍
