### PR TITLE
Fix user lookup spamming the api, and throwing

### LINKED ISSUE #1551: Don't spam the api on user lookup - debounce calls
When we lookup users right now for the sharing modal, we're spamming the api and fire a request for every single character types. This is leading to the calls ultimately failing and the UI to hang. 

We should make sure this is debounced.

### PR DESCRIPTION
**Pull request by Tbaut**
closes #1551 

Took me forever, but finally found the best solution :)

### CODE REVIEW

File: packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx [hunk 1]
```diff
@@ -240,6 +240,8 @@ const CreateOrEditSharedFolderModal = ({ mode, isModalOpen, onClose, bucketToEdi
                 alignContent: "start"
               })
             }}
+            loadingMessage={t`Loading`}
+            noOptionsMessage={t`No user found for this username`}
```
Comment (tanmoyAtb) [inline packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx]: Since we can add addresses here as well, we may leave out the `username` part

File: packages/files-ui/src/Components/Modules/Settings/Profile.tsx [hunk 2]
```diff
@@ -217,7 +217,7 @@ const ProfileView = () => {
       addToast({ title: t`Profile updated`, type: "success" })
       setUpdatingProfile(false)
     } catch (error) {
-      addToast({ title: error, type: "error" })
+      error instanceof Error && addToast({ title: error.message, type: "error" })
```
Comment (tanmoyAtb) [inline packages/files-ui/src/Components/Modules/Settings/Profile.tsx:220]: Should we add an alternate case where `error` in not an instanceOf Error ?

**Review by tanmoyAtb — APPROVED** [review]
Looks all good to go! 
left some concerns in comments

File: packages/files-ui/src/Components/Modules/Settings/Profile.tsx (hunk 2 above)
Comment (Tbaut) [reply packages/files-ui/src/Components/Modules/Settings/Profile.tsx:220]: in 99% of the cases, it will be I guess. I didn't research this lint error in detail, but this problem occurs because error went from type `any` to type `unknown`.

File: packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx (hunk 1 above)
Comment (Tbaut) [reply packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx]: sure
```suggestion
            noOptionsMessage={t`No user found for this query.`}
```

File: packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx [hunk 3]
```diff
@@ -259,7 +261,10 @@ const CreateOrEditSharedFolderModal = ({ mode, isModalOpen, onClose, bucketToEdi
                 minHeight: 90,
                 alignContent: "start"
               })
-            }}/>
+            }}
+            loadingMessage={t`Loading`}
+            noOptionsMessage={t`No user found for this username`}
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx]:
```suggestion
            noOptionsMessage={t`No user found for this query.`}
```

File: packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx [hunk 4]
```diff
@@ -365,7 +364,10 @@ const ShareModal = ({ close, file, filePath }: IShareFileProps) => {
                         minHeight: 90,
                         alignContent: "start"
                       })
-                    }}/>
+                    }}
+                    loadingMessage={t`Loading`}
+                    noOptionsMessage={t`No user found for this username`}
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx]:
```suggestion
            noOptionsMessage={t`No user found for this query.`}
```

File: packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx [hunk 5]
```diff
@@ -381,7 +383,10 @@ const ShareModal = ({ close, file, filePath }: IShareFileProps) => {
                         minHeight: 90,
                         alignContent: "start"
                       })
-                    }}/>
+                    }}
+                    loadingMessage={t`Loading...`}
+                    noOptionsMessage={t`No user found for this username`}
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx]:
```suggestion
            noOptionsMessage={t`No user found for this query.`}
```

**Review by FSM1 — APPROVED** [review]

**Review by RyRy79261 — APPROVED** [review]

File: packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx [hunk 6]
```diff
@@ -367,7 +366,10 @@ const ShareModal = ({ close, file, filePath }: IShareFileProps) => {
                         minHeight: 90,
                         alignContent: "start"
                       })
-                    }}/>
+                    }}
+                    loadingMessage={t`Loading`}
+            noOptionsMessage={t`No user found for this query.`}
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx]:
```suggestion
                    loadingMessage={t`Loading`}
                    noOptionsMessage={t`No user found for this query.`}
```

File: packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx [hunk 7]
```diff
@@ -383,7 +385,10 @@ const ShareModal = ({ close, file, filePath }: IShareFileProps) => {
                         minHeight: 90,
                         alignContent: "start"
                       })
-                    }}/>
+                    }}
+                    loadingMessage={t`Loading...`}
+            noOptionsMessage={t`No user found for this query.`}
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx]:
```suggestion
                    noOptionsMessage={t`No user found for this query.`}
```
