### PR TITLE
[Fix] Remove the artificial 65 char limit and fix caption on black theme

### LINKED ISSUE #1874: Change # chars for uploaded files to unlimited
_[Adapted from Slack thread]_

Uploading a file with a super long name is fine until a user tries to rename it (even to a shorter name). It seems there’s a max # of chars we can input for names, but after shortening the title, the system still doesn't take the shorter renamed title (even after pressing ‘enter’).

Solution: Update # chars for uploaded files (and all relevant things) to be unlimited

@Tbaut @FSM1

### PR DESCRIPTION
**Pull request by Tbaut**
closes #1874 

after some tests, it seems that the limit in the name isn't enforced by the api side, for folders or shared folders (buckets) so I removed them all. While testing in dark mode I realize than we had a certainly long standing issue where the error message weren't readable, black on black. That's also fixed now

Before:
image

After
image

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

### CODE REVIEW

File: packages/files-ui/cypress/tests/file-management-spec.ts [hunk 1]
```diff
@@ -196,7 +196,7 @@ describe("File management", () => {
     })
 
     it("can rename a file with error handling", () => {
-      const newName = "awesome new name"
+      const newName = "awesome new name that is pretty long and it shouldn't matter that much anyway"
```
Comment (asnaith) [inline packages/files-ui/cypress/tests/file-management-spec.ts:199]: 👍

**Review by asnaith — APPROVED** [review]

**Review by FSM1 — APPROVED** [review]
