### PR TITLE
Fixed placeholder spacing

### LINKED ISSUE #1728: "Create Shared Folder" placeholder text has no padding (mobile)
**Description**
The "Create Shared Folder" placeholder text is very close to the edge of the input element it is within and would be neater with some extra padding. 

**Screenshots**

IMG_7EAFF2C796FB-1

### PR DESCRIPTION
**Pull request by RyRy79261**
closes #1728

### CODE REVIEW

**Review by FSM1 — APPROVED** [review]

File: packages/common-theme/src/Provider/ThemeSwitcherContext.tsx [hunk 1]
```diff
@@ -26,6 +28,8 @@ type ThemeSwitcherProps = {
 const ThemeSwitcher = ({ children, themes, storageKey = "cs.themeKey" }: ThemeSwitcherProps) => {
   const breakpoints = createBreakpoints({})
   const desktop = useMediaQuery(breakpoints.up("md"))
+  const tablet = useMediaQuery(breakpoints.up("sm"))
```
Comment (tanmoyAtb) [inline packages/common-theme/src/Provider/ThemeSwitcherContext.tsx:31]: question: with this implementation show the `tablet` variable as `true` in desktop screens ?
will this be better:
`const tablet = useMediaQuery(breakpoints.up("sm")) && useMediaQuery(breakpoints.down("md"))`

**Review by tanmoyAtb — COMMENTED** [review]
Leaving a comment about the `tablet` and `mobile` variables

File: packages/common-theme/src/Provider/ThemeSwitcherContext.tsx (hunk 1 above)
Comment (RyRy79261) [reply packages/common-theme/src/Provider/ThemeSwitcherContext.tsx:31]: Yeah so because desktop is an upward query, technically then we'd need to check if its between `xl` as well, though I'm not sure how many things we'd need to change to maintain that consistency

Comment (FSM1) [reply packages/common-theme/src/Provider/ThemeSwitcherContext.tsx:31]: This is basically the equivalent of the `between` operator in MUI

**Review by asnaith — APPROVED** [review]

File: packages/common-theme/src/Provider/ThemeSwitcherContext.tsx (hunk 1 above)
Comment (tanmoyAtb) [reply packages/common-theme/src/Provider/ThemeSwitcherContext.tsx:31]: yes, I would say keep the desktop as is, above `md`, 
keep the tablet and mobile between screen sizes !

Comment (RyRy79261) [reply packages/common-theme/src/Provider/ThemeSwitcherContext.tsx:31]: So personally, I would also prefer only the two concepts to query against, but since this is in the theme kit, I would want it to be a bit more consistent with what one would expect from the kit, so just the Desktop & Tablet, I'd have it provided within the consuming codebase

**Review by tanmoyAtb — APPROVED** [review]
