### PR TITLE
Handle successful local Crypto Payment

### LINKED ISSUE #1974: Crypto payment UI does not refresh after transaction is confirmed
**Description**
On the crypto payment modal - after clicking the “pay via metamask” button and signing the transaction in the metamask extension the button became disabled and displayed a spinner on it until the payment had been confirmed. 

Once the payment had been confirmed the spinner stopped and the button became enabled. The UI did not automatically update and I had to close the modal and refresh the browser in order to see the changes being reflected in the UI. 

**To Reproduce**
1. Go to settings > subscription tab
2. Choose an annual plan and navigate through the payment flow, choosing crypto as the payment method
3. Choose ethereum as the payment type
4. Click "Pay with metamask" (or click "Connect Wallet" first if displayed)
5. Sign the transaction in metamask and wait for the transaction confirmation

**Expected behavior**
It is expected that once the transaction has been confirmed in metamask that the UI updates, closing the crypto payment modal and showing the new plan details on the settings page. 

**Desktop (please complete the following information):**
- Not device / OS / browser specific

### PR DESCRIPTION
**Pull request by FSM1**
closes #1974 

---
Submission checklist: 

   

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

### CODE REVIEW

**Comment by asnaith** [comment]
We are going to need some more funds when this is ready for testing

**Comment by asnaith** [comment]
Sorry, clicked the wrong button and closed this by mistake...re-opening!

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx [hunk 1]
```diff
@@ -164,6 +166,14 @@ const PlanSuccess = ({ plan, onClose, planPrice }: IPlanSuccess) => {
           </Link>
         </Typography>
       </div>
+      {paymentMethod === "crypto" &&
+        <div className={classes.rowBox}>
+          <Typography>
+            Crypto payments may take a few minutes to be processed.
+            Your subscription will be updated after logging out
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx]:
```suggestion
            <Trans>Crypto payments may take a few minutes to be processed.
            Your subscription will be updated after logging out</Trans>
```

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx [hunk 2]
```diff
@@ -27,6 +28,10 @@ const useStyles = makeStyles(({ constants, breakpoints }: CSFTheme) =>
   })
 )
 
+type PayInvoiceModalSlides = "confirmPlan" |
+"planSuccess" |
+"cryptoPayment"
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx]:
```suggestion
type PayInvoiceModalSlides = "confirmPlan" | "planSuccess" | "cryptoPayment"
```

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx [hunk 3]
```diff
@@ -40,14 +45,16 @@ const PayInvoiceModal = ({ onClose, invoiceId }: IChangeProductModal) => {
...
+  const [slide, setSlide] = useState<PayInvoiceModalSlides | undefined>()
 
   const payInvoice = useCallback(() => {
     if (!invoiceToPay) return
 
     try {
       setPayingInvoice(true)
       setErrorMessage(undefined)
-      filesApiClient.payInvoice(invoiceToPay.uuid).then(refreshInvoices)
+      filesApiClient.payInvoice(invoiceToPay.uuid).then(refreshInvoices).then(() => setSlide("planSuccess"))
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx]:
```suggestion
      filesApiClient.payInvoice(invoiceToPay.uuid)
        .then(() => {
          setSlide("planSuccess")
          refreshInvoices()
        )
```

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx [hunk 4]
```diff
@@ -56,8 +63,18 @@ const PayInvoiceModal = ({ onClose, invoiceId }: IChangeProductModal) => {
...
+      setSlide(invoiceToPay?.payment_method === "crypto"
+        ? "cryptoPayment"
+        : "confirmPlan"
+      )
+    }
+  }, [invoiceToPay, slide])
+
   if (!invoiceToPay) return null
 
+
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx]:
```suggestion
```

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx [hunk 5]
```diff
@@ -71,18 +88,25 @@ const PayInvoiceModal = ({ onClose, invoiceId }: IChangeProductModal) => {
...
-        />
+      {slide === "cryptoPayment" && <CryptoPayment
+        onClose={onClose}
+        onSuccess={() => setSlide("planSuccess")}
+      />}
+      {slide === "confirmPlan" && <ConfirmPlan
+        plan={{ ...invoiceToPay.product, prices: [invoiceToPay.product.price] }}
+        planPrice={invoiceToPay.product.price}
+        goToSelectPlan={() => undefined }
+        goToPaymentMethod={() => undefined }
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx]: I know it was there before, I must have missed it in a previous review, but this looks dodgy. Why not set this to `undefined` right away? I'd fix that in another PR unless we have good reasons to do what we do.

**Review by Tbaut — COMMENTED** [review]
Left some nits, I can't test this properly for crypto, I'll let Andrew do this.

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx (hunk 5 above)
Comment (FSM1) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx]: the current method signatures all expect a function. I guess that these parameters could be marked as optional

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx [hunk 6]
```diff
@@ -56,6 +64,15 @@ const PayInvoiceModal = ({ onClose, invoiceId }: IChangeProductModal) => {
     }
   }, [filesApiClient, invoiceToPay, refreshInvoices])
 
+  useEffect(() => {
+    if (!slide) {
+      setSlide(invoiceToPay?.payment_method === "crypto"
+        ? "cryptoPayment"
+        : "confirmPlan"
```
Comment (tanmoyAtb) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx:71]: Is there an easy way of getting to this state where a pending invoice has `creditCard` as payment method ? 

Note : if the user has no default card (removed it for example) and he sees the confirm modal, he could still be able press the `confirm plan` button and that wouldn't work. I haven't been able to test this though.

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx [hunk 7]
```diff
@@ -164,6 +166,14 @@ const PlanSuccess = ({ plan, onClose, planPrice }: IPlanSuccess) => {
           </Link>
         </Typography>
       </div>
+      {paymentMethod === "crypto" &&
+        <div className={classes.rowBox}>
+          <Typography>
+            <Trans>Crypto payments may take a few minutes to be processed.
+            Your subscription will be updated after logging out</Trans>
```
Comment (tanmoyAtb) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx]: Should this really be logging out ? I might be missing sth !

Comment (FSM1) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx]: The problem here is we have no idea when to refresh the subscription (after the successful completion of the transfer) - There are too many moving parts in the equation between the Coinbase backend, coinbase webhook as well as the files api processing the webhook and updating subscription.

Simply calling `refreshSubscription` even after a noticeable (5 block) delay is not enough to ensure that the subscription has been updated.

We could of course have a polling mechanism, but this feels like overkill.

Simply refreshing the page after a minute or two would obviously resolve any lingering state, but achieves the exact same effect as logging out and back in again.

Comment (tanmoyAtb) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx]: I see, makes sense. So logout is simply to make the refresh the states and give it some time. Seeing crypto payments would be rare plus its annual, this should be good enough.

Comment (Tbaut) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx]: Good point, should we advise to refresh instead? It requires less steps than logging out.

Comment (FSM1) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx]: What about just advising the user that the subscription update will reflect on next login (whether via refresh or a new session)

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx (hunk 6 above)
Comment (FSM1) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx:71]: unfortunately now that the API is checking whether the transaction is successful before updating the subscription, the only way to test this would be to upgrade, and then after the upgrade change the card to one that will fail, and wait till the next billing run.

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx (hunk 7 above)
Comment (tanmoyAtb) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx]: That sounds better to me.

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx (hunk 6 above)
Comment (tanmoyAtb) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx:71]: Sounds right. We can add a small safety measure. On the `confirm plan change` button, keep it disabled if there is no `defaultCard`.

Comment (FSM1) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx:71]: added a check for this

**Review by Tbaut — APPROVED** [review]
:+1: Test passing locally as well for the subscription :)

**Review by tanmoyAtb — APPROVED** [review]
