### PR TITLE
Toasts refactor

### LINKED ISSUE #1465: Download / Upload toasts notifications overlap each other
**Description**
Upload / Download toast modal dialogs overlap and do not stack on top of each other

**Steps to Reproduce**
1. Login to Files
2. Start the download for a file (choose a large sixe file so the toast is present for long enough)
3. As one file is downloading start uploading a large file 

**Observed behavior**
The toasts are displayed in the same area so one overlaps the other when both actions are being performed at the same time

**Expected behavior**
The toasts should stack so that both are readable to the user

**Video**

https://user-images.githubusercontent.com/3982665/130301261-9f370e33-5806-4a9e-87cd-7e2e293408db.mov

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version : 92.0.4515.107

### PR DESCRIPTION
**Pull request by tanmoyAtb**
closes #1465 

Created #1494 for cancellation operations.

### CODE REVIEW

File: packages/common-components/src/Toasts/ToastContent.tsx [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+
+const useStyles = makeStyles(({ constants, palette, animation }: ITheme) => {
+  return createStyles({
+    boxContainer: {
+      backgroundColor: palette.additional["gray"][3],
+      margin: constants.generalUnit,
+      border: `1px solid ${palette.additional["gray"][6]}`,
+      padding: constants.generalUnit * 2,
+      borderRadius: 4,
+      position: "relative",
```
Comment (RyRy79261) [inline packages/common-components/src/Toasts/ToastContent.tsx:17]: @tanmoyAtb  We'll just need some theming override classes added to the common themes for these please :)

File: packages/common-components/src/Toasts/ToastContent.tsx [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+    },
+    progressCrossButton: {
+      marginLeft: constants.generalUnit,
+      cursor: "pointer",
+      width: constants.generalUnit * 2,
+      height: constants.generalUnit * 2
+    },
+    closeIcon: {
+      position: "absolute",
+      right: "-8px",
```
Comment (RyRy79261) [inline packages/common-components/src/Toasts/ToastContent.tsx]: Just to consider, since this is half the size, you could set right n top to 0 and use `transform: translate(-50%,-50%)` and use `constants.generalUnit * 2` for the height n width, then for the svg `constants.generalUnit` 

This would make it shift with a standard value or alternatively a specific constant for the close icon settings

File: packages/common-components/src/Toasts/ToastContext.tsx [hunk 3]
```diff
@@ -0,0 +1,209 @@
...
+      left: 0
+    },
+    bottomLeftAppearBox: {
+      animation: `$slideRight ${animation.translate}ms`,
+      [breakpoints.down("sm")]: {
+        animation: `$slideUp ${animation.translate}ms`
+      }
+    },
+    "@keyframes slideRight": {
+      from: { transform: "translate(-100%)" },
```
Comment (RyRy79261) [inline packages/common-components/src/Toasts/ToastContext.tsx]: Just a note on practice here, if you aren't making use of one of the short hand fields, you've effectively made it incompatible with animations that might need that property, so I'd recommend setting this to `translateY(-100%)` to prevent collisions

File: packages/common-components/src/index.ts [hunk 4]
```diff
@@ -31,7 +31,8 @@ export * from "./Spinner"
 export * from "./Table"
 export * from "./Tabs"
 export * from "./TagsInput"
-export * from "./Toaster"
+// export * from "./Toaster"
```
Comment (RyRy79261) [inline packages/common-components/src/index.ts]:
```suggestion
```

Comment (RyRy79261) [reply packages/common-components/src/index.ts]: Assuming that the toaster is not gonna be used again, I'd removed it entirely, can retrieve from the commit prior to this PR if needed

**Review by RyRy79261 — APPROVED** [review]
Just want to confirm that the toast for File-ui is meant to be at the top right, otherwise left some comments for consideration

File: packages/common-components/src/Toasts/ToastContent.tsx (hunk 1 above)
Comment (tanmoyAtb) [reply packages/common-components/src/Toasts/ToastContent.tsx:17]: Ahh yes, forgot about those !

**Comment by FSM1** [comment]
Something in the new theme file seems to be breaking the tests. Can be replicated by initiating a rebuild of the common components.

File management -- desktop -- can addremove multiple files and upload (failed)

File: packages/common-components/src/Toasts/types.ts [hunk 5]
```diff
@@ -0,0 +1,21 @@
+
+export type ToastType = "success" | "error"
+
+export type ToastPosition = "top-left" | "top-right" | "bottom-left" | "bottom-right"
```
Comment (FSM1) [inline packages/common-components/src/Toasts/types.ts]:
```suggestion
export type ToastPosition = "topLeft" | "topRight" | "bottomLeft" | "bottomRight"
```

File: packages/common-components/src/Toasts/ToastContext.tsx [hunk 6]
```diff
@@ -0,0 +1,209 @@
...
+}
+
+const ToastContext = React.createContext<ToastContext | undefined>(
+  undefined
+)
+
+const ToastProvider = ({
+  children,
+  autoDismiss = true,
+  defaultPosition = "top-right",
```
Comment (FSM1) [inline packages/common-components/src/Toasts/ToastContext.tsx]:
```suggestion
  defaultPosition = "topRight",
```

File: packages/common-components/src/Toasts/ToastContext.tsx [hunk 7]
```diff
@@ -0,0 +1,209 @@
...
+            className={clsx(
+              classes.toastWrapper,
+              classes[`${positionedToasts.identifier}Container`]
+            )}
+          >
+            {positionedToasts.toasts.map((toast) => (
+              <div
+                key={toast.id}
+                className={classes[`${positionedToasts.identifier}AppearBox`]}
+              >
```
Comment (FSM1) [inline packages/common-components/src/Toasts/ToastContext.tsx]: Updates types, variable names
  
  ```suggestion
const positionedToasts: Record<ToastPosition, Array<Toast>> = useMemo(() => ({
    topRight: toasts.filter((toast) => toast.toastPosition === "topRight"),
    topLeft: toasts.filter((toast) => toast.toastPosition === "topLeft"),
    bottomRight: toasts.filter((toast) => toast.toastPosition === "bottomRight"),
    bottomLeft: toasts.filter((toast) => toast.toastPosition === "bottomLeft"),
  }), [toasts])
  return (
    <ToastContext.Provider
      value={{
        addToast,
        updateToast,
        removeToast,
        toasts
      }}
    >
      {(Object.keys(positionedToasts) as ToastPosition[]).map((position) => (
        !!positionedToasts[position].length && (
          <div
            key={position}
            className={clsx(
              classes.toastWrapper,
              classes[`${position}Container`]
            )}
          >
            {positionedToasts[position].map((toast) => (
              <div
                key={toast.id}
                className={classes[`${position}AppearBox`]}
              >
```

File: packages/common-components/src/stories/Toasts.stories.tsx [hunk 8]
```diff
@@ -0,0 +1,155 @@
...
+  return (
+    <ToastProvider
+      autoDismiss={boolean("default auto dismiss", true)}
+      dismissTimeout={number("default dismiss timeout", 4000)}
+    >
+      <ToastNotificationDemo
+        toast={{
+          title: text("title", "Upload Started"),
+          type: "success",
+          toastPosition: select("position", ["top-left", "top-right", "bottom-left", "bottom-right"], "top-right"),
```
Comment (FSM1) [inline packages/common-components/src/stories/Toasts.stories.tsx]:
```suggestion
          toastPosition: select("position", ["topLeft", "topRight", "bottomLeft", "bottomRight"], "topRight"),
```

File: packages/common-components/src/stories/Toasts.stories.tsx [hunk 9]
```diff
@@ -0,0 +1,155 @@
...
+  return (
+    <ToastProvider
+      autoDismiss={boolean("default auto dismiss", true)}
+      dismissTimeout={number("default dismiss timeout", 4000)}
+    >
+      <ToastMultipleNotificationDemo
+        toast={{
+          title: text("title", "Upload Started"),
+          type: "success",
+          toastPosition: select("position", ["top-left", "top-right", "bottom-left", "bottom-right"], "top-right"),
```
Comment (FSM1) [inline packages/common-components/src/stories/Toasts.stories.tsx]:
```suggestion
          toastPosition: select("position", ["topLeft", "topRight", "bottomLeft", "bottomRight"], "topRight"),
```

File: packages/files-ui/src/Contexts/FilesContext.tsx [hunk 10]
```diff
@@ -382,71 +341,71 @@ const FilesProvider = ({ children }: FilesContextProps) => {
...
     }
 
+    const toastParams: ToastParams = {
+      title: plural(files.length, {
+        one: `Encrypting and uploading ${files.length} file`,
+        other: `Encrypting and uploading ${files.length} files`
+      }) as string,
+      type: "success",
+      progress: 0,
+      toastPosition: "bottom-right"
```
Comment (FSM1) [inline packages/files-ui/src/Contexts/FilesContext.tsx]:
```suggestion
      toastPosition: "bottomRight"
```

File: packages/files-ui/src/Contexts/FilesContext.tsx [hunk 11]
```diff
@@ -523,58 +482,48 @@ const FilesProvider = ({ children }: FilesContextProps) => {
...
+        const totalFileNumber = fullStructure.length
+
+        const toastParams: ToastParams = {
+          title: plural(fullStructure.length, {
+            one: `Downloading ${fullStructure.length} file`,
+            other: `Downloading ${fullStructure.length} files`
+          }) as string,
+          type: "success",
+          progress: 0,
+          toastPosition: "bottom-right"
```
Comment (FSM1) [inline packages/files-ui/src/Contexts/FilesContext.tsx]:
```suggestion
          toastPosition: "bottomRight"
```

File: packages/files-ui/src/Contexts/FilesContext.tsx [hunk 12]
```diff
@@ -599,49 +548,40 @@ const FilesProvider = ({ children }: FilesContextProps) => {
...
-        fileName: itemToDownload.name,
-        totalFileNumber: 1,
-        complete: false,
-        error: false,
-        progress: 0
+      const toastParams: ToastParams = {
+        title: t`Downloading file - ${itemToDownload.name}`,
+        type: "success",
+        progress: 0,
+        toastPosition: "bottom-right"
```
Comment (FSM1) [inline packages/files-ui/src/Contexts/FilesContext.tsx]:
```suggestion
        toastPosition: "bottomRight"
```

File: packages/files-ui/src/Contexts/FilesContext.tsx [hunk 13]
```diff
@@ -744,97 +685,77 @@ const FilesProvider = ({ children }: FilesContextProps) => {
...
-    const transferProgress: TransferProgress = {
-      id: toastId,
-      complete: false,
-      error: false,
+    const toastParams: ToastParams = {
+      title: t`Sharing your file (Downloading)`,
+      type: "success",
       progress: 0,
-      operation: "Download"
+      toastPosition: "bottom-right"
```
Comment (FSM1) [inline packages/files-ui/src/Contexts/FilesContext.tsx]:
```suggestion
      toastPosition: "bottomRight"
```

**Review by FSM1 — APPROVED** [review]
Some minor Type improvements, that I left suggestions for, but otherwise stellar work 🥇 

PS. Will need a lint after you accept the suggestions

**Review by FSM1 — CHANGES_REQUESTED** [review]
Improved the types a bit, left some suggestions

**Comment by tanmoyAtb** [comment]
> Improved the types a bit, left some suggestions

Updated all the types and got things linted :)

**Comment by asnaith** [comment]
Hi Tanmoy, I pushed an update for the toast identifier. The tests are passing again now.

Screen Shot 2021-09-07 at 5 57 45 PM

File: packages/common-components/src/Toasts/ToastContent.tsx [hunk 14]
```diff
@@ -0,0 +1,155 @@
...
+        height: constants.generalUnit
+      },
+      ...overrides?.Toasts?.closeIcon
+    }
+  })
+})
+
+export interface ToastContentProps {
+  toast: ToastContentData
+  onClose(): void
```
Comment (Tbaut) [inline packages/common-components/src/Toasts/ToastContent.tsx]:
```suggestion
  onClose: () => void
```

File: packages/common-components/src/Toasts/ToastContent.tsx [hunk 15]
```diff
@@ -0,0 +1,155 @@
...
+const ToastContent = ({ toast, onClose }: ToastContentProps) => {
+  const classes = useStyles()
+  const { type, title, progress, subtitle, onProgressCancel } = toast
+  return (
+    <div
+      className={clsx(classes.root)}
+      data-testid={`toast-${toast.testId}`}
+    >
+      {progress !== undefined
+        ? <div>
```
Comment (Tbaut) [inline packages/common-components/src/Toasts/ToastContent.tsx]: is there any reason for the additionnal div here?

File: packages/common-components/src/Toasts/ToastContent.tsx [hunk 16]
```diff
@@ -0,0 +1,155 @@
...
+            />
+            {onProgressCancel &&
+              <CloseCirceSvg
+                className={classes.progressCrossButton}
+                onClick={onProgressCancel}
+              />
+            }
+          </div>
+        </div>
+        : <div>
```
Comment (Tbaut) [inline packages/common-components/src/Toasts/ToastContent.tsx]: Same question here regarding the div. Also there's some code duplication here (the whole title container, would be good to have this stored in a variable)

File: packages/common-components/src/Toasts/ToastContext.tsx [hunk 17]
```diff
@@ -0,0 +1,196 @@
...
+    setToasts((toasts) => ([
+      ...toasts,
+      { id,
+        ...toastParams,
+        toastPosition: toastParams.toastPosition || defaultPosition
+      }
+    ]))
+
+    const isProgressToast = toastParams.progress !== undefined
+    const shouldDismiss = toastParams.autoDismiss !== undefined ? toastParams.autoDismiss : autoDismiss
```
Comment (Tbaut) [inline packages/common-components/src/Toasts/ToastContext.tsx]: can use `toastParams.autoDismiss || autodismiss`
```suggestion
    const shouldDismiss = toastParams.autoDismiss || autoDismiss
```

File: packages/common-components/src/Toasts/ToastContext.tsx [hunk 18]
```diff
@@ -0,0 +1,196 @@
...
+    }
+
+    return id
+  }, [autoDismiss, dismissTimeout, defaultPosition])
+
+  const updateToast = useCallback((toastId: string, toastParams: ToastParams, startDismissal?: boolean) => {
+    const dismissTimeOut = toastParams.dismissTimeout || dismissTimeout
+    if (startDismissal) {
+      setTimeout(() => {
+        setToasts((toasts) => toasts.filter((toast) => toast.id !== toastId))
```
Comment (Tbaut) [inline packages/common-components/src/Toasts/ToastContext.tsx]: you can call `removeToast` here instead.
```suggestion
        removeToast(toast.id)
```

File: packages/common-components/src/Toasts/types.ts [hunk 19]
```diff
@@ -0,0 +1,22 @@
...
+export type ToastType = "success" | "error"
+
+export type ToastPosition = "topLeft" | "topRight" | "bottomLeft" | "bottomRight"
+export interface Toast {
+  id: string
+  type: ToastType
+  title: string
+  subtitle?: string
+  progress?: number
+  onProgressCancel?(): void
```
Comment (Tbaut) [inline packages/common-components/src/Toasts/types.ts]: use `() => void` notation
```suggestion
  onProgressCancel?: () => void
```

File: packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx [hunk 20]
```diff
@@ -185,16 +185,16 @@ const CSFFileBrowser: React.FC<IFileBrowserModuleProps> = () => {
       }
     }
     if (hasFolder) {
-      addToastMessage({
-        message: "Folder uploads are not supported currently",
-        appearance: "error"
+      addToast({
+        title: "Folder uploads are not supported currently",
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx]: translation
```suggestion
        title: t`Folder uploads are not supported currently`,
```

File: packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx [hunk 21]
```diff
@@ -186,16 +186,16 @@ const SharedFileBrowser = () => {
       }
     }
     if (hasFolder) {
-      addToastMessage({
-        message: "Folder uploads are not supported currently",
-        appearance: "error"
+      addToast({
+        title: "Folder uploads are not supported currently",
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx]: translation
```suggestion
        title: t`Folder uploads are not supported currently`,
```

File: packages/files-ui/src/Contexts/FilesContext.tsx [hunk 22]
```diff
@@ -650,23 +591,24 @@ const FilesProvider = ({ children }: FilesContextProps) => {
...
-          type: "remove",
-          payload: { id: toastId }
-        })
-      }, REMOVE_TOAST_DELAY)
+      setDownloadsInProgress(false)
       return Promise.resolve()
     } catch (error) {
-      dispatchDownloadsInProgress({ type: "error", payload: { id: toastId } })
+      updateToast(toastId, {
+        title: t`Download failed`,
```
Comment (Tbaut) [inline packages/files-ui/src/Contexts/FilesContext.tsx]: I wonder if we should give more info right away here. Also we should console.error the error.

File: packages/common-components/src/Toasts/ToastContext.tsx [hunk 23]
```diff
@@ -0,0 +1,196 @@
...
+  autoDismiss?: boolean
+  dismissTimeout?: number
+  defaultPosition?: ToastPosition
+  children: React.ReactNode | React.ReactNode[]
+}
+
+interface ToastContext {
+  addToast(toastParams: ToastParams): string
+  updateToast(toastId: string, toastParams: ToastParams, startDismissal?: boolean): void
+  removeToast(toastId: string): void
```
Comment (Tbaut) [inline packages/common-components/src/Toasts/ToastContext.tsx]:
```suggestion
  addToast: (toastParams: ToastParams) => string
  updateToast: (toastId: string, toastParams: ToastParams, startDismissal?: boolean) => void
  removeToast: (toastId: string) => void
```

File: packages/common-components/src/Toasts/ToastContext.tsx [hunk 24]
```diff
@@ -0,0 +1,196 @@
...
+  toasts: Toast[]
+}
+
+const ToastContext = React.createContext<ToastContext | undefined>(
+  undefined
+)
```
Comment (Tbaut) [inline packages/common-components/src/Toasts/ToastContext.tsx:96]: nit
```suggestion
const ToastContext = React.createContext<ToastContext | undefined>(undefined)
```

File: packages/common-components/src/stories/Toasts.stories.tsx [hunk 25]
```diff
@@ -0,0 +1,155 @@
+import React from "react"
+import {
+  ToastContent,
+  ToastParams,
+  ToastProvider,
+  useToasts
+} from "../Toasts"
```
Comment (Tbaut) [inline packages/common-components/src/stories/Toasts.stories.tsx]: nit
```suggestion
import { ToastContent, ToastParams, ToastProvider, useToasts } from "../Toasts"
```

File: packages/files-ui/cypress/support/page-objects/homePage.ts [hunk 26]
```diff
@@ -11,7 +11,7 @@ export const homePage = {
   uploadButton: () => cy.get("[data-cy=button-upload-file]"),
   moveSelectedButton: () => cy.get("[data-testId=button-move-selected-file]"),
   deleteSelectedButton: () => cy.get("[data-testId=button-delete-selected-file]"),
-  uploadStatusToast: () => cy.get("[data-cy=upload-status-toast-message]", { timeout: 10000 }),
+  uploadStatusToast: () => cy.get("[data-testId=toast-upload-status]", { timeout: 10000 }),
```
Comment (Tbaut) [inline packages/files-ui/cypress/support/page-objects/homePage.ts:14]: I can't see this defined anywhere (I might have missed it). Ping me if you need any help on that, happy to give a hand.

**Review by Tbaut — COMMENTED** [review]
Wow such a great amount of goodness, really like it!
Found a couple nits, but pretty much nothing compared to the size of this PR!
Just a note for another PR, File deletion and recovery toasts (and possibly others) are still at the top, which feels inconsistent to me.

File: packages/files-ui/cypress/support/page-objects/homePage.ts (hunk 26 above)
Comment (Tbaut) [reply packages/files-ui/cypress/support/page-objects/homePage.ts:14]: oh looks like Andrew got that sorted.

**Review by FSM1 — APPROVED** [review]

**Comment by tanmoyAtb** [comment]
> Hi Tanmoy, I pushed an update for the toast identifier. The tests are passing again now.
> 
> Screen Shot 2021-09-07 at 5 57 45 PM

Thanks a lot for taking care of that @asnaith

File: packages/common-components/src/Toasts/ToastContent.tsx (hunk 15 above)
Comment (tanmoyAtb) [reply packages/common-components/src/Toasts/ToastContent.tsx]: removed it !

File: packages/common-components/src/Toasts/ToastContent.tsx (hunk 16 above)
Comment (tanmoyAtb) [reply packages/common-components/src/Toasts/ToastContent.tsx]: Removed the extra div!
I did not get the part about titleContainer and duplication, can you elaborate ?

File: packages/files-ui/src/Contexts/FilesContext.tsx (hunk 22 above)
Comment (tanmoyAtb) [reply packages/files-ui/src/Contexts/FilesContext.tsx]: Added the console, and better info !

File: packages/common-components/src/Toasts/ToastContext.tsx (hunk 18 above)
Comment (tanmoyAtb) [reply packages/common-components/src/Toasts/ToastContext.tsx]: Actually thats what I tried first!
But somehow the function keeps a reference of older toasts state from when it got initialized, and causes weird behaviour,
moved to this implementation later!

**Comment by tanmoyAtb** [comment]
> Wow such a great amount of goodness, really like it!
> Found a couple nits, but pretty much nothing compared to the size of this PR!
> Just a note for another PR, File deletion and recovery toasts (and possibly others) are still at the top, which feels inconsistent to me.

Thanks for the amazing feedbacks!
I changed the default position to bottom right, All toasts in in place now.

File: packages/common-components/src/Toasts/ToastContext.tsx (hunk 18 above)
Comment (Tbaut) [reply packages/common-components/src/Toasts/ToastContext.tsx]: ah ok interesting, the fact that `toast` is part of the dep array should prevent that. I'll take a closer look just for my information.

Comment (Tbaut) [reply packages/common-components/src/Toasts/ToastContext.tsx]: @tanmoyAtb, would you mind telling me in what case this happened?, I can't reproduce the problem you mentioned, I've monitored the call to `removeToast` for instance when I delete several files, or upload several files (not at the same time), and all the toasts get removed in the right order.

File: packages/files-ui/src/App.tsx [hunk 27]
```diff
@@ -101,7 +101,8 @@ const App = () => {
       >
         <CssBaseline />
         <LanguageProvider availableLanguages={availableLanguages}>
-          <ToasterProvider autoDismiss>
+          <ToastProvider autoDismiss
+            defaultPosition="bottomRight">
```
Comment (Tbaut) [inline packages/files-ui/src/App.tsx]:
```suggestion
          <ToastProvider
            autoDismiss
            defaultPosition="bottomRight"
          >
```

File: packages/common-components/src/Toasts/ToastContent.tsx (hunk 16 above)
Comment (Tbaut) [reply packages/common-components/src/Toasts/ToastContent.tsx]: I thought there was some duplication with the `CheckCircleIcon` repeated for instance, and the `title` being common to both when there's a `progress` and when there isn't. But it's a nit and would maybe make the code more complex to read, so it's def. fine to leave it as is.

File: packages/common-components/src/Toasts/ToastContext.tsx (hunk 18 above)
Comment (tanmoyAtb) [reply packages/common-components/src/Toasts/ToastContext.tsx]: hey @Tbaut, so try starting two uploads parallelly, 
both toasts would get dismissed whenever the first toast gets dismissed!

Comment (Tbaut) [reply packages/common-components/src/Toasts/ToastContext.tsx]: Yup that's what I did, and it's looking fine for me:

https://user-images.githubusercontent.com/33178835/132722698-7884b1e8-c5f2-4341-8c69-e341e1c830d5.mp4

File: packages/common-components/src/Toasts/ToastContext.tsx [hunk 28]
```diff
@@ -0,0 +1,196 @@
...
+      }
+    ]))
+
+    const isProgressToast = toastParams.progress !== undefined
+    const shouldDismiss = toastParams.autoDismiss || autoDismiss
+    const dismissTimeOut = toastParams.dismissTimeout || dismissTimeout
+
+    if (shouldDismiss && !isProgressToast) {
+      setTimeout(() => {
+        setToasts((toasts) => toasts.filter((toast) => toast.id !== id))
```
Comment (Tbaut) [inline packages/common-components/src/Toasts/ToastContext.tsx]: I also replaced this one, and tested thoroughly, looking ok too. I'll check on brave.
```suggestion
        removeToast(id)
```

Comment (Tbaut) [reply packages/common-components/src/Toasts/ToastContext.tsx]: Tried with brave, and looks good.

File: packages/common-components/src/Toasts/ToastContext.tsx (hunk 18 above)
Comment (tanmoyAtb) [reply packages/common-components/src/Toasts/ToastContext.tsx]: I think you might see the weird behaviour if you start uploads of similar size, where the startDismiss fires at close times!
In this recording, you can see toasts reappearing after uploads complete!

https://user-images.githubusercontent.com/10713353/132729395-a1c08678-6006-408c-868d-be178a3fad60.mov

File: packages/common-components/src/Toasts/ToastContext.tsx (hunk 28 above)
Comment (tanmoyAtb) [reply packages/common-components/src/Toasts/ToastContext.tsx]: There is one more thing you can try to see the weird behaviour!
There is a `Toasts Demo` under toasts in storybook, try opening a number of toasts there

File: packages/common-components/src/Toasts/ToastContext.tsx (hunk 18 above)
Comment (Tbaut) [reply packages/common-components/src/Toasts/ToastContext.tsx]: Thanks a lot, I got it, the sate that the `setTimeout` restores, is the one from a couple seconds ago, because of the closure. This is a very good example where we would actually need to have a `useRef` instead of `useState`. Allow me to hold this PR a couple more hours, for the sake of having behavior we 100% understand without duplication. I'll create a PR pointing to this one.

Comment (Tbaut) [reply packages/common-components/src/Toasts/ToastContext.tsx]: Ok here we go, I've submitted here: https://github.com/ChainSafe/ui-monorepo/pull/1513
Let me know what you think.
For more info about the closure thing, you can have a look here for instance https://github.com/facebook/react/issues/14010

**Comment by Tbaut** [comment]
Please check https://github.com/ChainSafe/ui-monorepo/pull/1513 @tanmoyAtb it fixes my grumbles.

**Comment by tanmoyAtb** [comment]
> Please check #1513 @tanmoyAtb it fixes my grumbles.

all on track now!

**Review by Tbaut — APPROVED** [review]
:tada: oh yeah, yet again an awesome one Tanmoy!
