### PR TITLE
Pay invoice manually

### LINKED ISSUE #1884: Handle failed credit card payments gracefully
When an Stripe payment fails, the user should be able to retry the payment with the existing card, or update their card and initiate a payment using the new card.

The user should also be blocked from changing their subscription if the current subscription is in status `pending_update` - currently even if the payment failed the subscription status is set to `active` leading to the user having access to the `change plan` functionality, even though it would most likely fail.

Failed payments can be tested using card number `4000000000000341`

### LINKED ISSUE #1891: "Pay Now" link does not return user to "Pay with crypto" modal
**Description**
"Pay Now" button does not return user to payment modal when clicked on the billing history page, it works as intended on the subscription tab within settings. 

**Steps to Reproduce**
1. Go to settings > click "Change Plan"
2. Select a higher tier with annual billing and crypto as the payment method
3. Exit payment flow without paying to leave an unpaid invoice on the account
4. Click the "All Invoices" link to go to the billing history page
5. Click the "Pay Now" button

**Observed behavior**
Click the "Pay Now" link has no effect, nothing happens 

**Expected behavior**
User should be returned to the "Pay with Crypto" modal

**Console Error**
Not seeing any call to the "pay" endpoint on the api when the link is clicked on the billing history page (but see it when clicked on the subscription tab)

**Video**

https://user-images.githubusercontent.com/3982665/151647019-f87f74c7-b260-4c72-93b2-2970094bdf64.mp4

**Desktop / Mobile**
- Universal issue on all devices / layouts.

### PR DESCRIPTION
**Pull request by FSM1**
closes #1884
closes #1891 
---
Testing the card payment flow for failed payments has become more difficult as no invoice or upgrade is processed if the initial payment fails. This PR handles the case where initial payment fails, displaying an error message to the user.

Submission checklist: 

#### Layout
- [x] Change looks good in the desktop web ui
- [x] Change looks good in the mobile web ui

#### Theme
- [x] Components / elements inspected in light mode 
- [x] Components / elements inspected in dark mode

### CODE REVIEW

**Comment by Tbaut** [comment]
lint and lgtm-com are complaining a little :D

**Comment by FSM1** [comment]
> lint and lgtm-com are complaining a little :D

not anymore >.<

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx [hunk 1]
```diff
@@ -2,7 +2,7 @@ import React, { useMemo } from "react"
 import { makeStyles, createStyles } from "@chainsafe/common-theme"
 import { CSFTheme } from "../../../../../Themes/types"
 import { Product, ProductPrice } from "@chainsafe/files-api-client"
-import { Button, InfoCircleIcon, CreditCardIcon, Divider, formatBytes, Typography } from "@chainsafe/common-components"
+import { Button, CreditCardIcon, Divider, formatBytes, Typography } from "@chainsafe/common-components"
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx]: Same
```suggestion
import { Button, InfoCircleIcon, CreditCardIcon, Divider, formatBytes, Typography } from "@chainsafe/common-components"
```

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx [hunk 2]
```diff
@@ -302,28 +302,14 @@ const ConfirmPlan = ({
...
-          <InfoCircleIcon className={classes.icon} />
-          <Trans>
-            Once you proceed, your account is expected to make a payment within 60 minutes. If no payment is received
-            , your plan will not change.
-          </Trans>
-        </Typography>
-      </div>
-      }
-      {isSubscriptionError &&
+      {subscriptionErrorMessage &&
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx:319]: This should stay, that's a merge conflict gone wrong I think
```suggestion
      {paymentMethod === "crypto" && <div className={classes.rowBox}>
        <Typography
          variant="body1"
          component="p"
          className={classes.warningText}
        >
          <InfoCircleIcon className={classes.icon} />
          <Trans>
            Once you proceed, your account is expected to make a payment within 60 minutes. If no payment is received
            , your plan will not change.
          </Trans>
        </Typography>
      </div>
      }
      {subscriptionErrorMessage &&
```

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx [hunk 3]
```diff
@@ -30,45 +29,30 @@ const useStyles = makeStyles(({ constants }: ITheme) =>
...
-          data-cy="header-billing-history"
-        >
-          <Trans>Billing history</Trans>
-        </Typography>
-        <Typography
-          variant="body1"
-          component="p"
-          className={classes.link}
-        >
-          <Link to={ROUTE_LINKS.BillingHistory}>
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx]: The "all invoice button is gone now?

**Review by Tbaut — CHANGES_REQUESTED** [review]
Found some conflicts resolution gone bad!

**Comment by asnaith** [comment]
Nice. The error message looks good and pay now button on the billing history page now returns the user to the payment flow. 

I noticed an issue with the error message being retained after leaving and returning to the modal but I realized it was a pre-existing issue so I've created a separate issue for that (#1922)

**Review by asnaith — APPROVED** [review]

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx [hunk 4]
```diff
@@ -44,7 +76,21 @@ const PayInvoiceModal = ({ onClose }: IChangeProductModal) => {
       testId="pay-invoice"
       onClose={onClose}
     >
-      <CryptoPayment />
+      {!invoiceToPay
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx]: I think an early return such as `if (!invoiceToPay) return null` would be nicer, and than have 1 ternary would work

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx [hunk 5]
```diff
@@ -52,23 +52,19 @@ const BillingHistory = () => {
...
           </Link>
         </Typography>
-      </div>
-      {isPendingInvoice && <Typography
-        variant="body1"
-        component="p"
-        className={classes.billingText}
-      >
+      </div >
+      {(isPendingInvoice || invoices?.find(i => i.status === "open")) &&
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx]: I've seen this in the billing context too, should we have a boolean in the context `isOpenInvoice` with this?

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx [hunk 6]
```diff
@@ -12,6 +12,7 @@ import PlanSuccess from "./PlanSuccess"
 import DowngradeDetails from "./DowngradeDetails"
 import { PaymentMethod } from "../../../../../Contexts/BillingContext"
 import CryptoPayment from "../Common/CryptoPayment"
+import { t } from "@lingui/macro"
```
Comment (Tbaut) [inline packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx:15]:
```suggestion
import { t } from "@lingui/macro"

```

**Review by Tbaut — COMMENTED** [review]
Just looked at the code, found a couple nits, I'll play with it now and check for https://github.com/ChainSafe/ui-monorepo/issues/1922

File: packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx (hunk 5 above)
Comment (FSM1) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx]: not sure I get what you mean here

Comment (Tbaut) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx]: sorry, I mean `invoices?.find(i => i.status === "open")`. This is an info that is recalculated elsewhere (I've see the same snippet in the `BillingContext`). So I think we should expose a `isOpenInvoice` flag in the context to reuse it.

Comment (FSM1) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx]: updated though I chose not to use a flag, but rather expose the entire object since the invoice details are used in the billing context. I really don't see what this adds in terms of readability.

Comment (Tbaut) [reply packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx]: It's not that much about readability (it's prob. harder to read), I'd say it's more about reusing things. Having a complex expression in a `if`, and the fact that we had this exact expression elsewhere was what made me comment.

**Review by Tbaut — APPROVED** [review]
looks good, I'll push a PR right away for what Andrew found
